[project]
name = "01-unit-conversion-in-python"
version = "0.1.0"
description = "This project is created in python and st using latest python package manager UV"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
